version: '2'
services:
  jenkins-caddy:
    image: stanchan/jenkins-caddy:latest
    environment:
      CADDY_TLS_MODE: caddy_tls_selfsigned
    ports:
      - "80:80"
      - "443:443"
      - "2015:2105"
    networks:
      test:
        aliases:
          - jenkins
          - nexus
    volumes:
      - ./data/caddy:/root/.caddy
  jenkins-hashicorp-virtualbox-slave:
    image: stanchan/jenkins-hashicorp-virtualbox-slave:latest
    environment:
      JENKINS_NAME: jenkins-hashicorp-virtualbox-slave
      JENKINS_SCHEME: http
      JENKINS_SERVER: jenkins-master
      JENKINS_SLAVE_PORT: 8080
      JENKINS_EXECUTORS: 2
    networks:
      test:
        aliases:
          - jenkins-docker-slave
  jenkins-golang-slave:
    image: stanchan/jenkins-golang-slave:latest
    environment:
      JENKINS_NAME: jenkins-golang-slave
      JENKINS_SCHEME: http
      JENKINS_SERVER: jenkins-master
      JENKINS_SLAVE_PORT: 8080
      JENKINS_EXECUTORS: 2
    networks:
      test:
        aliases:
          - jenkins-golang-slave
  jenkins-swarm-slave:
    image: stanchan/jenkins-swarm-slave:latest
    environment:
      JENKINS_NAME: jenkins-swarm-slave
      JENKINS_SCHEME: http
      JENKINS_SERVER: jenkins-master
      JENKINS_SLAVE_PORT: 8080
      JENKINS_EXECUTORS: 2
    networks:
      test:
        aliases:
          - jenkins-swarm-slave
  jenkins-docker-slave:
    image: stanchan/jenkins-docker-slave:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    networks:
      test:
        aliases:
          - jenkins-docker-slave
    dns_search:
      - test
  nexus:
    image: stanchan/nexus:latest
    ports:
      - "8081:8081"
    networks:
      test:
        aliases:
          - nexus-master
  jenkins-master:
    image: stanchan/jenkins-master:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      test:
        aliases:
          - jenkins-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
networks:
  test:
    driver: bridge
